# Generated by Django 4.1.6 on 2023-02-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0002_remove_product_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_image',
            new_name='image',
        ),
    ]
