# Generated by Django 4.1.6 on 2023-02-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0003_rename_brand_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='unit_price',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='store',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='posApp.currency'),
        ),
    ]
