# Generated by Django 4.1.6 on 2023-02-28 13:25

from django.db import migrations
import posApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', posApp.models.CustomUserManager()),
            ],
        ),
    ]
