# Generated by Django 4.1.6 on 2023-03-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='posApp.currency'),
        ),
    ]
