# Generated by Django 4.1.6 on 2023-03-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_alter_store_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='order',
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_change',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_payed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='grand_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='sub_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name='sale',
            table='Sales',
        ),
    ]
