# Generated by Django 4.1.6 on 2023-03-08 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_sale_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('total_detail', models.FloatField()),
                ('product', models.ForeignKey(blank=True, db_column='product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posApp.product')),
                ('sale', models.ForeignKey(blank=True, db_column='sale', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posApp.sale')),
            ],
            options={
                'db_table': 'SaleDetails',
            },
        ),
    ]
