# Generated by Django 4.1.6 on 2023-03-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0011_saledetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
