# Generated by Django 4.1.6 on 2023-03-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0012_delete_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='order',
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='sale',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posApp.sale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='quantity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(blank=True, default=None, null=True)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('product', models.ForeignKey(blank=True, db_column='product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posApp.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.purchase')),
            ],
            options={
                'db_table': 'PurchaseDetail',
            },
        ),
    ]
