# Generated by Django 4.1.6 on 2023-03-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0014_sale_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='sup_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='code_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='sup_city',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='sup_details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='sup_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='sup_mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='sup_country',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='sup_name',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='sup_state',
        ),
    ]
