# Generated by Django 4.1.6 on 2023-03-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0015_rename_sup_address_supplier_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
    ]
