# Generated by Django 4.1.6 on 2023-03-15 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0016_rename_customer_name_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posApp.store'),
        ),
    ]
