# Generated by Django 4.1.6 on 2023-03-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0019_alter_saledetail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='Active', max_length=100, verbose_name='Status of the product'),
        ),
    ]
