# Generated by Django 4.1.6 on 2023-03-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0022_alter_category_status_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
    ]
